## train/validation/test split 구성

1. source별 최종 데이터 개수 확인
2. source 비율을 유지하면서 train/val/test split
3. patient/file 단위 중복 방지
4. split CSV 저장
5. Dataset 클래스에서 split CSV를 읽도록 구성

- train: 70%
- validation: 15%
- test: 15%

In [5]:
import pandas as pd
from pathlib import Path

WORK_DIR = Path(r"C:\Users\comds\Desktop\졸업작품\vscode_script")

df_t11_t12_final = pd.read_pickle(
    WORK_DIR / "df_t11_t12_final_candidates.pkl"
)

In [6]:
from sklearn.model_selection import train_test_split
import pandas as pd

df = df_t11_t12_final.copy()

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["source"],
    random_state=42,
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["source"],
    random_state=42,
)

train_df = train_df.copy()
val_df = val_df.copy()
test_df = test_df.copy()

train_df["split"] = "train"
val_df["split"] = "val"
test_df["split"] = "test"

df_split = pd.concat([train_df, val_df, test_df], ignore_index=True)

display(pd.crosstab(df_split["split"], df_split["source"]))
display(pd.crosstab(df_split["split"], df_split["source"], normalize="index"))

df_split.to_csv(
    "df_t11_t12_train_val_test_split.csv",
    index=False,
    encoding="utf-8-sig",
)

df_split.to_pickle("df_t11_t12_train_val_test_split.pkl")

source  COLONOG  COVID-19  MSD-T10
split
test        113         6       22
train       526        26      105
val         113         5       23

source   COLONOG  COVID-19   MSD-T10
split
test    0.801418  0.042553  0.156028
train   0.800609  0.039574  0.159817
val     0.801418  0.035461  0.163121

In [14]:
import pandas as pd
from pathlib import Path

WORK_DIR = Path(r"C:\Users\comds\Desktop\졸업작품\vscode_script")

df2 = pd.read_pickle(
    WORK_DIR / "df_spacing_final.pkl"
)
df2.loc[df2['source']=="COVID-19",:].head()

,source,patient_id,file_name,shape_x,shape_y,shape_z,spacing_x,spacing_y,spacing_z,physical_x_mm,physical_y_mm,physical_z_mm,slice_count
752,COVID-19,volume-covid19-A-0011_ct,volume-covid19-A-0011_ct.nii.gz,512,512,296,0.741,0.741,1.000000,379.391998,379.391998,296.000000,296
753,COVID-19,volume-covid19-A-0013_ct,volume-covid19-A-0013_ct.nii.gz,512,512,208,0.449,0.449,0.799988,229.888000,229.888000,166.397461,208
754,COVID-19,volume-covid19-A-0014_ct,volume-covid19-A-0014_ct.nii.gz,512,512,286,0.741,0.741,1.000000,379.391998,379.391998,286.000000,286
755,COVID-19,volume-covid19-A-0016_ct,volume-covid19-A-0016_ct.nii.gz,512,512,361,0.741,0.741,1.000000,379.391998,379.391998,361.000000,361
756,COVID-19,volume-covid19-A-0025_ct,volume-covid19-A-0025_ct.nii.gz,512,512,61,0.846,0.846,5.000000,433.152008,433.152008,305.000000,61